<a href="https://colab.research.google.com/github/HR-Supaero/deep-learning/blob/main/demo_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔎 Retrieval-Augmented Generation (RAG) Demo Notebook

Welcome! This notebook demonstrates **RAG systems** step by step:
- 📄 Document ingestion  
- 🧠 Embedding & indexing  
- 🔍 Retrieval  
- 🤖 LLM-based generation

# Retrieval Augmented Generation

[Faiss documentation](https://faiss.ai/index.html)

In [1]:
# Run those install if you are using colab
!pip install faiss-gpu-cu12
!pip install -q transformers sentence-transformers pypdf
!pip install evaluate rouge_score
!pip install -qU ragas langchain-google-genai langchain-community datasets
!pip install langchain_qdrant
!pip install fastembed-gpu

Collecting faiss-gpu-cu12
  Downloading faiss_gpu_cu12-1.13.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: numpy<3,>=2 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (25.0)
Requirement already satisfied: nvidia-cuda-runtime-cu12>=12.1.105 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (12.6.77)
Requirement already satisfied: nvidia-cublas-cu12>=12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (12.6.4.1)
Downloading faiss_gpu_cu12-1.13.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (48.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 15.9 MB/s eta 0:00:00
Installing collected packages: faiss-gpu-cu12
Successfully installed faiss-gpu-cu12-1.13.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 329.1/329.1 kB 18.1 MB/s eta 0:00:00
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.4 MB/s eta 0:00:00
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=0c0f3356dde9125e819eab569d6a2ac53e34cee1e9d784926cd1a06198494712
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score, evaluate
Successfully installed evaluate-0.4.6 rouge_score-0.1.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 69.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 47.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 55.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.4/177.4 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 109.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.8/358.8 kB 38.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 6.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
Collecting langchain_qdrant
  Downloading langchain_qdrant-1.1.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain_qdrant) (1.2.7)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain_qdrant) (2.12.3)
Collecting qdrant-client<2.0.0,>=1.15.1 (from langchain_qdrant)
  Downloading qdrant_client-1.16.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (0.6.6)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain_qdrant) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain_qdrant) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain_qdrant) (0.4.2)
Requirement already satisfied: grpcio>=1.41.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (1.76.0)
Requirement already satisfied: httpx>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (0.28.1)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (2.0.2)
Collecting portalocker<4.0,>=2.7.0 (from qdrant-client<2.0.0,>=1.15.1->langchain_qdrant)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: protobuf>=3.20.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (5.29.5)
Requirement already satisfied: urllib3<3,>=1.26.14 in /usr/local/lib/python3.12/dist-packages (from qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (2.5.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (4.3.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (0.25.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client<2.0.0,>=1.15.1->langchain_qdrant) (4.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain_qdrant) (3.4.4)
Downloading langchain_qdrant-1.1.0-py3-none-any.whl (24 kB)
Downloading qdrant_client-1.16.2-py3-none-any.whl (377 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.2/377.2 kB 33.0 MB/s eta 0:00:00
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, qdrant-client, langchain_qdrant
Successfully installed langchain_qdrant-1.1.0 portalocker-3.2.0 qdrant-client-1.16.2
Collecting fastembed-gpu
  Downloading fastembed_gpu-0.7.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=0.20 in /usr/local/lib/python3.12/dist-packages (from fastembed-gpu) (0.36.0)
Collecting loguru<0.8.0,>=0.7.2 (from fastembed-gpu)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: mmh3<6.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from fastembed-gpu) (5.2.0)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from fastembed-gpu) (2.0.2)
Collecting onnxruntime-gpu!=1.20.0,>=1.17.0 (from fastembed-gpu)
  Downloading onnxruntime_gpu-1.23.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: pillow<12.0,>=10.3.0 in /usr/local/lib/python3.12/dist-packages (from fastembed-gpu) (11.3.0)
Collecting py-rust-stemmers<0.2.0,>=0.1.0 (from fastembed-gpu)
  Downloading py_rust_stemmers-0.1.5-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: requests<3.0,>=2.31 in /usr/local/lib/python3.12/dist-packages (from fastembed-gpu) (2.32.5)
Requirement already satisfied: tokenizers<1.0,>=0.15 in /usr/local/lib/python3.12/dist-packages (from fastembed-gpu) (0.22.2)
Requirement already satisfied: tqdm<5.0,>=4.66 in /usr/local/lib/python3.12/dist-packages (from fastembed-gpu) (4.67.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed-gpu) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed-gpu) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed-gpu) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed-gpu) (6.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed-gpu) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed-gpu) (1.2.0)
Collecting coloredlogs (from onnxruntime-gpu!=1.20.0,>=1.17.0->fastembed-gpu)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime-gpu!=1.20.0,>=1.17.0->fastembed-gpu) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime-gpu!=1.20.0,>=1.17.0->fastembed-gpu) (5.29.5)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime-gpu!=1.20.0,>=1.17.0->fastembed-gpu) (1.14.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31->fastembed-gpu) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31->fastembed-gpu) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31->fastembed-gpu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31->fastembed-gpu) (2026.1.4)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime-gpu!=1.20.0,>=1.17.0->fastembed-gpu)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime-gpu!=1.20.0,>=1.17.0->fastembed-gpu) (1.3.0)
Downloading fastembed_gpu-0.7.4-py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 13.5 MB/s eta 0:00:00
Downloading loguru-0.7.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 8.8 MB/s eta 0:00:00
Downloading onnxruntime_gpu-1.23.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (300.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.5/300.5 MB 1.6 MB/s eta 0:00:00
Downloading py_rust_stemmers-0.1.5-cp312-cp312-manylinux_2_28_x86_64.whl (324 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.8/324.8 kB 33.4 MB/s eta 0:00:00
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 6.2 MB/s eta 0:00:00
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 11.9 MB/s eta 0:00:00
Installing collected packages: py-rust-stemmers, loguru, humanfriendly, coloredlogs, onnxruntime-gpu, fastembed-gpu
Successfully installed coloredlogs-15.0.1 fastembed-gpu-0.7.4 humanfriendly-10.0 loguru-0.7.3 onnxruntime-gpu-1.23.2 py-rust-stemmers-0.1.5

In [2]:
# Imports
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM
import time
from tqdm.notebook import tqdm
import pandas as pd
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate
import evaluate

# 🍼 Toy example

In [3]:
# Parameters
chunk_size = 50
k = 2             # Top k docs

In [4]:
documents = [
    "Ernest Hemingway was born in Oak Park, Illinois, in 1899. He was an American novelist, short-story writer, and journalist.",
    "The middle ear is the portion of the ear internal to the eardrum, and external to the oval window of the inner ear.",
    "The Sun Also Rises is a 1926 novel by American writer Ernest Hemingway that involves a group of American and British expatriates.",
    "The three ossicles of the middle ear are the malleus, incus, and stapes, which transfer sound vibrations."
]

⚗ Embedding Model

In [5]:
# Load embedding model
embed_model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

🖌 Generation model

In [6]:
gen_model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(gen_model_name)
generator = AutoModelForCausalLM.from_pretrained(gen_model_name)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

🛠 First architecture

In [7]:
# Divide the docs into chunks
def chunker_v0(text, chunk_size):
    words = text.split()
    return [" ".join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]

all_chunks = []
for doc in documents:
    all_chunks.extend(chunker_v0(doc, chunk_size))

print(f"Total chunks created: {len(all_chunks)}")
print(all_chunks[0])

Total chunks created: 4
Ernest Hemingway was born in Oak Park, Illinois, in 1899. He was an American novelist, short-story writer, and journalist.

In [8]:
chunk_embeddings = embed_model.encode(all_chunks)
print(chunk_embeddings.shape)

# Create FAISS Index
dimension = chunk_embeddings.shape[1]
print(f"Latent space dim: {dimension}")
index = faiss.IndexFlatIP(dimension) # Inner Product (Cosine Similarity)
index.add(np.array(chunk_embeddings).astype('float32'))
faiss.write_index(index, "my_vector_store.index")
print("Vector store built and saved.")

(4, 384)
Latent space dim: 384
Vector store built and saved.

###◀ Retrieval

In [9]:
def retriever_v0(query, k=k):   # Will give us the best k documents
    query_vec = embed_model.encode([query])
    distances, indices = index.search(np.array(query_vec).astype('float32'), k)
    return [all_chunks[i] for i in indices[0]]

print(f"🔍 Searching for: Hemingway")
context = retriever_v0("Ernest Hemingway")
print(f"📖 Best {k} documents found: {context}")

🔍 Searching for: Hemingway
📖 Best 2 documents found: ['Ernest Hemingway was born in Oak Park, Illinois, in 1899. He was an American novelist, short-story writer, and journalist.', 'The Sun Also Rises is a 1926 novel by American writer Ernest Hemingway that involves a group of American and British expatriates.']

## Generation

In [10]:
def generate_answer(query, context):
    # Instruction-style prompt
    prompt = (
        f"You are a helpful assistant. Use the context below to answer the question.\n"
        f"Context: {' '.join(context)}\n"
        f"Question: {query}\n"
        f"Answer:"
    )

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
    outputs = generator.generate(**inputs, max_new_tokens=50, pad_token_id=tokenizer.eos_token_id)

    full_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract only the answer part
    return full_text.split("Answer:")[-1].strip()

In [11]:
def run_rag_dummy(user_query):
    print(f"🔍 Searching for: {user_query}")
    context = retriever_v0(user_query)
    print(f"📖 Context found: {context}")

    answer = generate_answer(user_query, context)
    return answer

# Test 1: Hemingway
print(f"Final Answer: {run_rag_dummy('Where was Hemingway born?')}")

print("-" * 30)

# Test 2: Biology
print(f"Final Answer: {run_rag_dummy('What are the bones in the middle ear?')}")

print("-" * 30)

# Test 3: Novel
print(f"Final Answer: {run_rag_dummy('When was The Sun Also Rises written ?')}")

print("-" * 30)

# Test 4: Random question
print(f"Final Answer: {run_rag_dummy('Who is the GOAT ? Messi Or Ronaldo ?')}")

🔍 Searching for: Where was Hemingway born?
📖 Context found: ['Ernest Hemingway was born in Oak Park, Illinois, in 1899. He was an American novelist, short-story writer, and journalist.', 'The Sun Also Rises is a 1926 novel by American writer Ernest Hemingway that involves a group of American and British expatriates.']
Final Answer: Ernest Hemingway was born in Oak Park, Illinois, in 1899. He was an American novelist, short-story writer, and journalist
------------------------------
🔍 Searching for: What are the bones in the middle ear?
📖 Context found: ['The middle ear is the portion of the ear internal to the eardrum, and external to the oval window of the inner ear.', 'The three ossicles of the middle ear are the malleus, incus, and stapes, which transfer sound vibrations.']
Final Answer: The bones of the middle ear are the bones of the middle ear. The bones of the middle ear are the bones of the middle ear. The bones of the middle ear are the bones of the middle ear. The bones of the middle ear are the
------------------------------
🔍 Searching for: When was The Sun Also Rises written ?
📖 Context found: ['The Sun Also Rises is a 1926 novel by American writer Ernest Hemingway that involves a group of American and British expatriates.', 'Ernest Hemingway was born in Oak Park, Illinois, in 1899. He was an American novelist, short-story writer, and journalist.']
Final Answer: The Sun Also Rises is a 1926 novel by American writer Ernest Hemingway. Ernest Hemingway was born in
------------------------------
🔍 Searching for: Who is the GOAT ? Messi Or Ronaldo ?
📖 Context found: ['The middle ear is the portion of the ear internal to the eardrum, and external to the oval window of the inner ear.', 'The three ossicles of the middle ear are the malleus, incus, and stapes, which transfer sound vibrations.']
Final Answer: The GOAT is the most important part of the ear. It is the part of the ear that is responsible for the sound of the music. It is the part of the ear that is responsible for the sound of the music. The GOAT is

Ok two observations:

While the first question is anwered correctly it seems the LLM just re gave us the context, while not wrong per se, it seems it was helped by the chunk size
It is like answering a question by not reformulating anything

The second answer is wrong though and it is perhaps a confirmation of what we suspected from the first response. The RAG doesnt understand the fact that "bones" and "Ossciles" are semantically similar.Worse, the second document is the best one for answering the question !

We observe what is called collapse, where instead of not returning an answer, the LLM still return a context

First of all lets try another chunker, since ours is pretty bruttal

##📚 Bigger example: Wikipedia questions

https://huggingface.co/datasets/rag-datasets/rag-mini-wikipedia

In [12]:
# Recursive chunker to preserve semantic sense

text_splitter = RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", " ", ""],  # Prioritize keeping paragraphs together, then sentences, then words.
    chunk_size=25,  # Aim for chunks of around 256 characters
    chunk_overlap=24,  # Overlap chunks by 16 characters to preserve context
)

def chunker_v1(documents):
  chunks = []
  for doc in documents:
      chunks.extend(text_splitter.split_text(doc))
  return chunks

chunks = chunker_v1(documents)
chunks[0]

'Ernest Hemingway was born'

Test on bigger data set

In [13]:
df_QnA = pd.read_parquet("hf://datasets/rag-datasets/rag-mini-wikipedia/data/test.parquet/part.0.parquet")

In [14]:
df_QnA.head()

                                             question     answer
id
0   Was Abraham Lincoln the sixteenth President of...        yes
2   Did Lincoln sign the National Banking Act of 1...        yes
4                    Did his mother die of pneumonia?         no
6       How many long was Lincoln's formal education?  18 months
8        When did Lincoln begin his political career?       1832

In [15]:
df_docs = pd.read_parquet("hf://datasets/rag-datasets/rag-mini-wikipedia/data/passages.parquet/part.0.parquet")
df_docs.head()

                                              passage
id
0   Uruguay (official full name in  ; pron.  , Eas...
1   It is bordered by Brazil to the north, by Arge...
2   Montevideo was founded by the Spanish in the e...
3   The economy is largely based in agriculture (m...
4   According to Transparency International, Urugu...

In [16]:
documents = df_docs['passage']
print(documents.shape)

(3200,)

In [17]:
questions = df_QnA['question']
print(questions.shape)

(918,)

In [18]:
answers_expected = df_QnA['answer']
print(answers_expected.shape)

(918,)

In [19]:
all_chunks = []
for doc in documents:
    all_chunks.extend(chunker_v0(doc, chunk_size))

print(f"Total chunks created: {len(all_chunks)}")

Total chunks created: 5781

In [20]:
# Load embedding model
embed_model = SentenceTransformer('all-MiniLM-L6-v2')
chunk_embeddings = embed_model.encode(all_chunks)

# Create FAISS Index
dimension = chunk_embeddings.shape[1]
print(f"Latent space dim: {dimension}")
index = faiss.IndexFlatIP(dimension) # Inner Product (Cosine Similarity)
index.add(np.array(chunk_embeddings).astype('float32'))

# Functional Tip: Save your index to disk
faiss.write_index(index, "my_vector_store.index")
print("Vector store built and saved.")

Latent space dim: 384
Vector store built and saved.

In [21]:
# Your existing code for RAG
import random
n_questions = 5     # Can be very long to execute

rag_answer = []
answers_rag = []


for q in tqdm(questions[0:n_questions], desc="Processing questions with RAG"):
    answers_rag.append(run_rag_dummy(q))

# Print a randomly selected response
print(answers_rag[random.randint(0, n_questions - 1)])

Processing questions with RAG:   0%|          | 0/5 [00:00<?, ?it/s]

🔍 Searching for: Was Abraham Lincoln the sixteenth President of the United States?
📖 Context found: ['Abraham Lincoln (February 12, 1809 â\x80\x93 April 15, 1865) was the sixteenth President of the United States, serving from March 4, 1861 until his assassination. As an outspoken opponent of the expansion of slavery in the United States, "[I]n his short autobiography written for the 1860 presidential campaign, Lincoln would', 'Young Abraham Lincoln']
🔍 Searching for: Did Lincoln sign the National Banking Act of 1863?
📖 Context found: ['legislation involved economic matters, including the first income tax and higher tariffs. Also included was the creation of the system of national banks by the National Banking Acts of 1863, 1864, and 1865, which allowed the creation of a strong national financial system. Congress created and Lincoln approved the Department', 'Lincoln believed in the Whig theory of the presidency, which left Congress to write the laws while he signed them, vetoing only those bills that threatened his war powers. Thus, he signed the Homestead Act in 1862, making millions of acres of government-held land in the West available for purchase']
🔍 Searching for: Did his mother die of pneumonia?
📖 Context found: ['An autopsy performed after his death revealed grave problems with his stomach and other organs of his abdomen, along with damage to his brain. Despite the autopsy, the cause of his continual poor health was never precisely determined, though speculation focuses on tuberculosis, stomach cancer, or a combination of the', "Lee was born. Theodore Roosevelt's mother Mittie died of Typhoid fever in the same house on the same day, Feb. 14, 1884. After the simultaneous deaths of his mother and wife, Roosevelt left his daughter in the care of his sister in New York and moved out to Dakota Territory."]
🔍 Searching for: How many long was Lincoln's formal education?
📖 Context found: ["Lincoln's formal education consisted of about 18 months of schooling. Largely self-educated, he read every book he could get his hands on, once walking. just to borrow one While his favorite book was The Life of George Washington, Lincoln mastered the Bible, Shakespeare, and English and American history, and developed", "* American School, Lincoln's economic views."]
🔍 Searching for: When did Lincoln begin his political career?
📖 Context found: ['Lincoln began his political career in 1832, at age 23, with an unsuccessful campaign for the Illinois General Assembly, as a member of the Whig Party. He ran eighth in a field of 13 candidates. The centerpiece of his platform was the undertaking of navigational improvements on the Sangamon River.', 'Young Abraham Lincoln']
Lincoln was born in 1832, in the town of Sangamon, Illinois. He was raised in the town of Lincoln, Illinois, and was educated at the University of Illinois. He was a member of the Illinois State Legislature, and was elected to

In [22]:
# Extract only the answer (first line or before \n)
extracted_answers = []
context_retrieved = []
for answer in answers_rag:
    # Split by newline and take the first part
    extracted = answer.split('\n')[0]
    context_retrieved.append(answer.split('\n')[1:])
    extracted_answers.append(extracted)
    context_retrieved.append(answer.split('\n')[1:])

print(len(extracted_answers))
print(extracted_answers)

5
['Yes, he was.', 'No. Lincoln signed the National Banking Act of 1863, which created the National Banking Act of 1863, which created the National Banking Act of 1863, which created the National Banking Act of 1863, which created the National Banking Act of 1863, which created the', 'No.', "Lincoln's formal education consisted of about 18 months of schooling. Largely self-educated, he read every book he could get his hands on, once walking. just to borrow one", 'Lincoln was born in 1832, in the town of Sangamon, Illinois. He was raised in the town of Lincoln, Illinois, and was educated at the University of Illinois. He was a member of the Illinois State Legislature, and was elected to']

In [23]:
top_k_context = []
for i in range(len(context_retrieved)):
  if (i%k == 0):
    top_k_context.append(context_retrieved[i])

print(len(top_k_context))
print(top_k_context)

5
[['Context: Abraham Lincoln (February 12, 1809 â\x80\x93 April 15, 1865) was the sixteenth President of the United States, serving from March 4, 1861 until his assassination. As an outspoken'], [], ['Question:'], ["Context: Lincoln's formal education consisted of about 18 months of schooling"], []]

In [24]:


# Ensure that the lengths match for creating the DataFrame
# questions, answers_expected, and extracted_answers are Series/lists, so slicing to match the processed length
eval_df = pd.DataFrame({
    'question': questions[0:len(extracted_answers)].values,
    'expected_answer': answers_expected[0:len(extracted_answers)].values,
    'context retrieved': top_k_context,
    'rag_answer': extracted_answers
})
display(eval_df.head())

,question,expected_answer,context retrieved,rag_answer
0,Was Abraham Lincoln the sixteenth President of...,yes,"[Context: Abraham Lincoln (February 12, 1809 â...","Yes, he was."
1,Did Lincoln sign the National Banking Act of 1...,yes,[],No. Lincoln signed the National Banking Act of...
2,Did his mother die of pneumonia?,no,[Question:],No.
3,How many long was Lincoln's formal education?,18 months,[Context: Lincoln's formal education consisted...,Lincoln's formal education consisted of about ...
4,When did Lincoln begin his political career?,1832,[],"Lincoln was born in 1832, in the town of Sanga..."

### RAG Quality Metrics

For a more nuanced evaluation of RAG quality, especially considering the semantic similarity and correctness of generated text, you can use metrics beyond simple exact matching:

*   **ROUGE-L**: These metrics compare the generated answer to the reference answer based on overlapping words or sequences. ROUGE-L (Longest Common Subsequence) is particularly good for assessing the main ideas.
*   **Embedding Similarity**: Mesuring the rag answer embedding angle to the expected response

Libraries like `evaluate` (Hugging Face) provide implementations for ROUGE and other generation metrics, which can be very helpful for a more comprehensive evaluation.

In [25]:

rouge = evaluate.load('rouge')

Downloading builder script: 0.00B [00:00, ?B/s]

In [26]:
rouge_score = rouge.compute(predictions=extracted_answers, references=answers_expected[0:n_questions])
print(f"Rouge Score {rouge_score}")

Rouge Score {'rouge1': np.float64(0.3190476190476191), 'rouge2': np.float64(0.013333333333333332), 'rougeL': np.float64(0.33452380952380956), 'rougeLsum': np.float64(0.33452380952380956)}

Comparasion with SOTA rouge scores

| Dataset | ROUGE-1 (Unigrams) | ROUGE-2 (Bigrams) | ROUGE-L (Longest Sequence) |
|---|---|---|---|
| CNN / Daily Mail | 44.0 – 47.5 | 20.0 – 22.0 | 41.0 – 44.5 |
| XSum (Extreme) | 45.0 – 48.0 | 22.0 – 25.0 | 37.0 – 40.0 |
| SAMSum (Dialogue) | 52.0 – 55.0 | 28.0 – 31.0 | 49.0 – 52.0 |
| Multi-News | 48.0 – 50.0 | 19.0 – 21.0 | 44.0 – 46.0 |

In [27]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

emb1 = model.encode("The sun is a star.")
emb2 = model.encode("Our solar system's center is a stellar body.")

cos_sim = util.cos_sim(emb1, emb2)
print(f"Semantic Similarity: {cos_sim.item():.4f}")

Semantic Similarity: 0.6063

In [28]:
avg_latent_angle = []
for rag, expected in zip(extracted_answers, answers_expected[0:n_questions]):
  emb1 = model.encode(rag)
  emb2 = model.encode(expected)
  cos_sim = util.cos_sim(emb1, emb2)
  avg_latent_angle.append(cos_sim.item())

avg_latent_angle = sum(avg_latent_angle) / len(avg_latent_angle)
print(f"Semantic Similarity: {avg_latent_angle:.4f}")

Semantic Similarity: 0.3123

#❓ What could be improved ?

* Try with bigger LLM models
* LLM based evaluation
* Play around the prompt template